 pipeline {
 agent {
 kubernetes {
 yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: gradle
      image: gradle:jdk8
      command:
        - sleep
      args:
        - 99d
restartPolicy: Never
"""
 }
 }
 stages {
 stage('Start the calculator') {
 steps {
 git url: 'https://github.com/pvvardhan/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
 container('gradle') {

 sh '''
 cd Chapter08/sample1
 curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
 chmod +x ./kubectl
 ./kubectl apply -f calculator.yaml
 ./kubectl apply -f hazelcast.yaml
 '''
 }
 }
 }
 stage('Executing curl tests') {
 steps {
 echo "Executing acceptance tests"
 container('gradle') {
 catchError {
 sh """
  test $(curl calculator-service:8080/sum?a=6\\&b=2)-eq 8 && echo 'pass' || echo 'fail'
  test $(curl calculator-service:8080/div?a=6\\&b=2)-eq 3 && echo 'pass' || echo 'fail'
  test $(curl calculator-service:8080/div?a=6\\&b=0)-eq 3 && echo 'Not divisable' || echo 'fail'
 """
 }
 }
 }
 }
 }
 post {
 always {
 echo 'pipeline completed'
 }
 }
 }