 pipeline {
 agent {
 kubernetes {
 yaml """
apiVersion: v1 
kind: Pod 
spec: 
      containers: 
      - name: gradle 
        image: gradle:jdk8 
        command: 
        - sleep 
        args: 
        - 99d 
        volumeMounts: 
        - name: shared-storage 
          mountPath: /mnt 
      - name: cloud-sdk 
        image: google/cloud-sdk 
        command: 
        - sleep 
        args: 
        - 9999999 
        volumeMounts: 
        - name: shared-storage 
          mountPath: /mnt 
        - name: google-cloud-key 
          mountPath: /var/secrets/google 
        env: 
        - name: GOOGLE_APPLICATION_CREDENTIALS 
          value: /var/secrets/google/umldevops-418804-82fcc4967114.json
      volumes: 
      - name: shared-storage 
        persistentVolumeClaim: 
          claimName: jenkins-pv-claim 
      - name: google-cloud-key 
        secret: 
          secretName: sdk-key 
restartPolicy: Never
"""
 }
 }
 stages {
 stage('Calculator smoke test') {
 steps {
 git url: 'https://github.com/pvvardhan/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
 container('gradle') {
 sh '''
 cd Chapter08/sample1
 curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
 chmod +x ./kubectl
 chmod +x gradlew
 ./kubectl apply -f calculator.yaml
 ./kubectl apply -f hazelcast.yaml
 sleep 20
 ./gradlew smokeTest -Dcalculator.url=http://calculator-service.devops-tools.svc.cluster.local:8080
 '''
 }
 }
 }
 stage('Deploy to cloud') {
 steps {
 container('cloud-sdk') {
 sh '''
 echo "Deploying to GKE"
 gcloud auth login --cred-file=$GOOGLE_APPLICATION_CREDENTIALS --no-launch-browser
 gcloud config set project umldevops-418804
 gcloud container clusters get-credentials umldevops-cluster --region us-central1 --project umldevops-418804
 echo 'namespaces in the GKE "prod" environment'
 kubectl get ns
 kubectl apply -f calculator.yaml 
 kubectl apply -f hazelcast.yaml
 '''
 }
 }
 }
 }
 post {
 always {
 echo 'pipeline completed - cleaning up resources in Gradle container'
 container('gradle') {
  sh '''
  cd Chapter08/sample1
  ./kubectl delete service hazelcast calculator-service -n devops-tools
  ./kubectl delete deployment hazelcast calculator-deployment -n devops-tools
  '''
  }
 }
 }
 }
 